export const destinations = [
  {
    id: 1,
    name: "Maldives",
    country: "Maldives",
    flag: "🇲🇻",
    continent: "Asia",
    duration: "7–14 nights",
    price: "from $4,200",
    priceNum: 4200,
    rating: 4.9,
    reviews: 847,
    tag: "Most Popular",
    tagColor: "#38bdf8",
    description: "Overwater villas floating above crystal lagoons. Wake to endless horizon and the sound of gentle waves.",
    highlights: ["Private overwater villa", "Coral reef diving", "Sunset dolphin cruise"],
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    availability: "Limited",
    category: "Island",
  },
  {
    id: 2,
    name: "Santorini",
    country: "Greece",
    flag: "🇬🇷",
    continent: "Europe",
    duration: "5–10 nights",
    price: "from $2,800",
    priceNum: 2800,
    rating: 4.8,
    reviews: 1240,
    tag: "Editor's Pick",
    tagColor: "#a78bfa",
    description: "Volcanic cliffs adorned with whitewashed architecture. Sunsets that redefine beauty.",
    highlights: ["Caldera-view villa", "Wine tasting tour", "Private yacht day"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    availability: "Available",
    category: "Cultural",
  },
  {
    id: 3,
    name: "Serengeti",
    country: "Tanzania",
    flag: "🇹🇿",
    continent: "Africa",
    duration: "8–12 nights",
    price: "from $6,500",
    priceNum: 6500,
    rating: 5.0,
    reviews: 423,
    tag: "Exclusive",
    tagColor: "#fbbf24",
    description: "Witness the greatest wildlife spectacle on Earth. Private bush camp under African skies.",
    highlights: ["Private game reserve", "Hot air balloon", "Bush dinner"],
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    availability: "Limited",
    category: "Safari",
  },
  {
    id: 4,
    name: "Kyoto",
    country: "Japan",
    flag: "🇯🇵",
    continent: "Asia",
    duration: "6–9 nights",
    price: "from $3,400",
    priceNum: 3400,
    rating: 4.9,
    reviews: 986,
    tag: "Cultural",
    tagColor: "#f87171",
    description: "Ancient temples shrouded in cherry blossoms. A journey into timeless Japanese culture.",
    highlights: ["Ryokan stay", "Tea ceremony", "Bamboo forest walk"],
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    availability: "Available",
    category: "Cultural",
  },
  {
    id: 5,
    name: "Patagonia",
    country: "Argentina",
    flag: "🇦🇷",
    continent: "South America",
    duration: "10–14 nights",
    price: "from $5,200",
    priceNum: 5200,
    rating: 4.8,
    reviews: 312,
    tag: "Adventure",
    tagColor: "#34d399",
    description: "The end of the world. Glaciers, condors, and mountains that pierce the sky.",
    highlights: ["Torres del Paine trek", "Glacier hike", "Eco lodge"],
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    availability: "Available",
    category: "Adventure",
  },
  {
    id: 6,
    name: "Amalfi Coast",
    country: "Italy",
    flag: "🇮🇹",
    continent: "Europe",
    duration: "7–10 nights",
    price: "from $3,900",
    priceNum: 3900,
    rating: 4.9,
    reviews: 1560,
    tag: "Romantic",
    tagColor: "#fb7185",
    description: "Cliffside villages tumbling into turquoise Mediterranean. La dolce vita, perfected.",
    highlights: ["Private villa", "Vespa tour", "Cooking class"],
    image: "https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800&q=80",
    availability: "Limited",
    category: "Cultural",
  },
];

export const experiences = [
  {
    id: 1,
    title: "Luxury Safari",
    subtitle: "Africa's Wild Heart",
    description: "Private game reserves. Expert guides. Unforgettable encounters with the Big Five.",
    icon: "🦁",
    price: "from $6,500",
    duration: "8 nights",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    color: "#f59e0b",
  },
  {
    id: 2,
    title: "Private Island",
    subtitle: "Your Own Paradise",
    description: "Complete seclusion on a private island. Staff of 12. No other guests. Ever.",
    icon: "🏝️",
    price: "from $12,000",
    duration: "5 nights",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    color: "#0ea5e9",
  },
  {
    id: 3,
    title: "City Escape",
    subtitle: "Urban Sophistication",
    description: "Penthouse suites. Michelin-star dining. Private city guides who know every secret door.",
    icon: "🌆",
    price: "from $2,400",
    duration: "4 nights",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    color: "#a78bfa",
  },
  {
    id: 4,
    title: "Adventure Tours",
    subtitle: "Controlled Adrenaline",
    description: "Helicopter landings on glaciers. White-water rafting through ancient canyons.",
    icon: "⛰️",
    price: "from $3,800",
    duration: "7 nights",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    color: "#34d399",
  },
  {
    id: 5,
    title: "Luxury Resorts",
    subtitle: "Absolute Indulgence",
    description: "Six-star resorts where your every desire is anticipated before you express it.",
    icon: "🏨",
    price: "from $1,800",
    duration: "Any",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
    color: "#f472b6",
  },
  {
    id: 6,
    title: "Hidden Gems",
    subtitle: "The Undiscovered",
    description: "Places that don't appear on travel blogs. Secret coves, private mountains, forgotten islands.",
    icon: "💎",
    price: "from $4,900",
    duration: "10 nights",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    color: "#22d3ee",
  },
];

export const reviews = [
  {
    id: 1,
    name: "Alexandra Chen",
    location: "New York, USA",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b9e7e72b?w=200&q=80",
    rating: 5,
    date: "February 2025",
    trip: "Maldives Private Villa",
    review: "Skybound transformed what I thought was a dream into the most extraordinary two weeks of my life. Every detail — from the seaplane transfer to the private chef — exceeded every expectation I didn't know I had.",
    verified: true,
  },
  {
    id: 2,
    name: "James Whitmore",
    location: "London, UK",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    rating: 5,
    date: "January 2025",
    trip: "Serengeti Safari",
    review: "I've traveled extensively for 30 years. This was different. Watching the Great Migration from our private camp, guided by someone who knows each animal by name — it changes you permanently.",
    verified: true,
  },
  {
    id: 3,
    name: "Sofia Marchetti",
    location: "Milan, Italy",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    rating: 5,
    date: "March 2025",
    trip: "Kyoto Cultural Journey",
    review: "The ryokan they selected felt like stepping into 16th-century Japan. The tea ceremony master spoke about his 40-year practice. I cried. Skybound doesn't book trips — they create pilgrimages.",
    verified: true,
  },
  {
    id: 4,
    name: "Marcus Rodriguez",
    location: "São Paulo, Brazil",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    rating: 5,
    date: "December 2024",
    trip: "Patagonia Adventure",
    review: "The logistics of getting to the Torres del Paine base camp with helicopter support and a private chef felt impossible — Skybound made it seamless. The team on the ground were extraordinary.",
    verified: true,
  },
  {
    id: 5,
    name: "Isabelle Dubois",
    location: "Paris, France",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    rating: 5,
    date: "April 2025",
    trip: "Amalfi Coast",
    review: "They reserved a section of a Positano restaurant for our anniversary dinner overlooking the lights reflecting in the sea. The sommelier had paired wines specific to my husband's taste profile. Impossible perfection.",
    verified: true,
  },
];

export const stats = [
  { value: 47, suffix: "K+", label: "Happy Travelers" },
  { value: 195, suffix: "", label: "Countries Covered" },
  { value: 12, suffix: "+", label: "Years of Excellence" },
  { value: 4.9, suffix: "/5", label: "Average Rating", decimal: true },
];

export const partners = [
  "Emirates", "Qatar Airways", "Singapore Airlines",
  "Four Seasons", "Aman Resorts", "Ritz-Carlton",
  "American Express", "Visa Infinite", "Mastercard Black",
];

export const blogPosts = [
  {
    id: 1,
    title: "The Last Untouched Islands You Can Still Visit",
    excerpt: "Before overtourism reaches these hidden gems, here's how to experience them with minimal footprint and maximum wonder.",
    category: "Hidden Gems",
    readTime: "8 min",
    date: "May 15, 2025",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    slug: "last-untouched-islands",
  },
  {
    id: 2,
    title: "How to Experience the Serengeti Migration Like a Naturalist",
    excerpt: "The difference between a tourist and a naturalist in the Serengeti isn't just knowledge — it's access. We explain both.",
    category: "Safari",
    readTime: "12 min",
    date: "April 22, 2025",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    slug: "serengeti-migration-guide",
  },
  {
    id: 3,
    title: "Japan Off-Season: Why Spring Crowds Miss the Best Month",
    excerpt: "Everyone goes for cherry blossoms. Discerning travelers go in November for autumn foliage, emptier temples, and exceptional sake.",
    category: "Cultural",
    readTime: "10 min",
    date: "March 10, 2025",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80",
    slug: "japan-november-guide",
  },
];

export const countryFlags = [
  { code: "JP", flag: "🇯🇵", name: "Japan" },
  { code: "IT", flag: "🇮🇹", name: "Italy" },
  { code: "MV", flag: "🇲🇻", name: "Maldives" },
  { code: "TZ", flag: "🇹🇿", name: "Tanzania" },
  { code: "AR", flag: "🇦🇷", name: "Argentina" },
  { code: "GR", flag: "🇬🇷", name: "Greece" },
  { code: "IS", flag: "🇮🇸", name: "Iceland" },
  { code: "PE", flag: "🇵🇪", name: "Peru" },
];
